About/urls.py
from django.urls import path
from .views import about
# Create your views here.
app_name='About'
urlpatterns = [
    path('',about, name='about'),
]

Accounts/urls.py
from django.urls import path
from .views import item_list
# # Create your views here.
# app_name='Accounts'
urlpatterns = [
    path('',item_list, name='item-list'),
]

Blog/urls.py
from django.urls import path
from .views import blog
# Create your views here.
app_name='Blog'
urlpatterns = [
    path('',blog, name='blog'),
]

Contact/urls.py
from django.urls import path
from .views import contact
# Create your views here.
app_name='Contact'
urlpatterns = [
    path('', contact, name='Contact'),
]

Home/urls.py
from argparse import Namespace
from django.urls import path

from Contact.views import contact
from .views import index
from Home import views
app_name='Home'
urlpatterns = [
    path('', index, name='index'),
    path('Contact/', contact, name='contact'),
    path('', index, name='index2'),
    path('', index, name='index3')
]

Pages/urls.py
from django.urls import path
from .views import faq
# Create your views here.
app_name='Pages'
urlpatterns = [
    path('', faq, name='faq'),
]

Shop/urls.py
from django.urls import path
from .views import card
# Create your views here.
app_name='Shop'
urlpatterns = [
    path('', card, name='card'),
]

zarito_stories/urls.py
#from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

#from zarito_stories.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Accounts/', include('allauth.urls')),
    path('Home/',include('Home.urls',namespace='Home')),
    path('Shop/',include('Shop.urls',namespace='Shop')),
    path('Pages/',include('Pages.urls',namespace='Pages')),
    path('Contact/',include('Contact.urls',namespace='Contact')),
    path('About/',include('About.urls',namespace='About')),
    path('Blog/',include('Blog.urls',namespace='Blog'))
    #path('Accounts/',include('Accounts.urls',namespace='Accounts'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [path('__debug__/',include(debug_toolbar.urls))]

Accounts/models.py
from django.conf import settings
from django.db import models
from sympy import ordered

class Item(models.Model):
    title = models.CharField(max_length=100)
    price=models.FloatField()
    def __str__(self):
        return self.title
    
class OrderItem(models.Model):
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    def __str__(self):
        return self.title
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date =models.DateTimeField()
    ordered = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username

Blog/models.py
from django.db import models

# Create your models here.

Contact/models.py
from django.db import models

# Create your models here.

Home/models.py
from django.db import models
from sqlalchemy import null

class About(models.Model):
    image = models.ImageField(upload_to='about/', null=True, blank=True)
    slogan = models.TextField(default="Innovative Solutions To Boost Your Projects estibulum ante ipsum primis in faucibus orci luctus et ultrices posuere consectetur sed, convallis at tellus. Donec rutrum congue leo eget malesuada. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vivamus suscipit tortor eget felis porttitor volutpat. Sed porttitor lectus nibh. Nulla porttitor accumsan tincidunt. Pellentesque in ipsum id orci porta dapibus. Praesent sapien massa, convallis a pellentesque nec,")
    

Pages/models.py
from django.db import models

# Create your models here.

Shop/models.py
from django.db import models

# Create your models here.

About/views.py
from django.shortcuts import render


# Create your views here.

def about(request):
    return render(request,'about-us.html')

Accounts/views.py
from django.shortcuts import render
from .models import Item
# # Create your views here.
def item_list(request):
    context ={
        'item': Item.objects.all()
    }
    return render(request, "item_list.html",context)

Blog/views.py
from django.shortcuts import render

# Create your views here.

def blog(request):
    return render(request,'blog.html')

Contact/views.py
from django.shortcuts import render

# Create your views here.

def contact(request):
    return render(request,'contact.html')

Home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'index.html')
def index2(request):
    return render(request,'index2.html')
def index3(request):
    return render(request,'index3.html')
def Contact(request):
    return render(request, 'contact.html')

Pages/views.py
from django.shortcuts import render

# Create your views here.

def faq(request):
    return render(request,'faq.html')

Shop/views.py
from string import capwords
from django.shortcuts import render

# Create your views here.

def card(request):
    return render(request,'card.html')

Home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
<!-- Mirrored from zairito-html.zainiktheme.com/demo/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 18 Dec 2021 08:46:24 GMT -->
<head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Zairito - eCommerce HTML Template</title>
        <meta name="description" content="Zairito - eCommerce HTML Template" />
        <meta name="keywords" content="business,eCommerce, Ecommerce, ecommerce, shop, shopify, shopify ecommerce, creative, woocommerce, design, gallery, minimal, modern, html, html5, responsive" />
        <meta name="author" content="Zairito" />

        <!-- fonts file -->
        <link href="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Allison&amp;display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Marcellus&amp;display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&amp;display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600;700&amp;display=swap" rel="stylesheet">

        <!-- css file  -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    
        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">

    </head>
    <body><!-- Preloader Area Start -->
        <div id="preloader">
            <div id="status">
                <img src="{% static 'images/preloader.svg' %}" alt="img" />
            </div>
        </div>
        <!-- Preloader Area End -->

        {%  block content  %}
        {% endblock content %}
        {% include 'includes/footer.html' %}
        {% include 'includes/navbar.html' %}
 <!-- shop map area start here  -->
 <div class="shop-map-area">
    <div class="shop-info">
        <div class="shop-info-left">
            <h2 class="shop-info-title">Local Pickup  Available</h2>
            <p  class="shop-info-sub-title">301 Front St Toronto, Canada</p>
            <ul class="shop-opaing-time">
                <li class="open-time">Mon - Fri, 8:30am - 10:30pm,</li>
                <li class="open-time">Sunday, 8:30am - 10:30pm</li>
            </ul>
        </div>
        <div class="shop-info-right">
            <span class="label">Shops Image</span>
        </div>
    </div>
    <div id="gmap" class="google-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1839.0179632416985!2d89.5538504127622!3d22.801132631062536!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39ff8f2b1098bf95%3A0xbce09c90b98f8380!2sJust%20Orders%20Khulna!5e0!3m2!1sen!2sbd!4v1636005141952!5m2!1sen!2sbd" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
</div>
<!-- shop map area start here  -->
        <!-- Page Load Popup Modal End -->
        <div class="modal fade bd-example-modal-lg theme-modal" id="popUpModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body modal1 modal-bg">
                     <div class="row"> 
                         <div class="col-12">
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                         </div>
                         <div class="col-lg-12">
                             <div class="row">
                                 <div class="col-lg-7 col-md-12">
                                    <div class="offer_modal_left">
                                        <img src="{% static 'images/zairito.png'  %}" alt="logo">
                                        <h3>SUBSCRIBE TO NEWSLETTER</h3>
                                        <p class="m-0">Subscribe to the Zairito mailing list to receive updates
                                            on new arrivals, special offers and our promotions.</p>
                                        <form>
                                            <div class="input-group mb-3">
                                                <input type="text" class="form-control" placeholder="Your email">
                                                <div class="input-group-append">
                                                    <button class="theme-btn-one btn-black-overlay btn_sm border-0">Subscribe</button>
                                                </div>
                                            </div>
                                            <div class="check_boxed_modal">
                                                <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
                                                <label for="vehicle1">Don't show this popup again</label>
                                            </div>
                                        </form>
                                    </div>
                                 </div>
                                 <div class="col-lg-5 col-md-12">
                                    <div class="offer_modal_img d-none d-lg-flex">
                                        <img src="{% static 'images/hero-banner-image-1.png' %}" alt="img">
                                    </div>
                                 </div>                        
                             </div>
                            
                         </div>
                     </div>
                    </div>
             </div>
          </div>
        </div>
        <!-- Page Load Popup Modal End -->
        
        <!-- Js file  -->
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>

<!-- Mirrored from zairito-html.zainiktheme.com/demo/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 18 Dec 2021 08:48:44 GMT -->
</html>

Home/templates/includes/footer.html
{% load static %}
  <!-- footer area start here -->
  <footer class="footer-area">
    <div class="footer-widget-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-3 col-lg-4 col-md-4 col-sm-4">
                    <div class="single-widget about-widget">
                        <a href="index.html" class="footer-brand-logo mb-25"> <img src="{% static 'images/footer-logo.png'%}" alt="footer-logo" /></a>
                        <p class="address-text">685 Market Street <br /> San Francisco, CA 94105, <br />United States</p>
                        <div class="block-content mb-30">
                            <p class="contact">Call us: 1.800.000.6690</p>
                            <p class="contact">Email: support@zainikthemes.com</p>
                        </div>
                        <ul class="social-media">
                            <li class="social-media-item"><a class="social-media-link" href="javascript:void(0)"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="social-media-item"><a class="social-media-link" href="javascript:void(0)"><i class="fab fa-skype"></i></a></li>
                            <li class="social-media-item"><a class="social-media-link" href="javascript:void(0)"><i class="fab fa-twitter"></i></a></li>
                            <li class="social-media-item"><a class="social-media-link" href="javascript:void(0)"><i class="fab fa-linkedin-in"></i></a></li>
                            <li class="social-media-item"><a class="social-media-link" href="javascript:void(0)"><i class="fab fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-8 col-md-8 col-sm-8">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="single-widget">
                                <h3 class="widget-title">Shop by</h3>
                                <ul class="widget-menu show">
                                    <li class="menu-item"><a class="menu-link" href="shop-grid-left-sidebar.html">Appliances</a></li>
                                    <li class="menu-item"><a class="menu-link" href="shop-grid-right-sidebar.html">Computers & Laptops</a></li>
                                    <li class="menu-item"><a class="menu-link" href="shop-grid.html">Cameras</a></li>
                                    <li class="menu-item"><a class="menu-link" href="shop-list.html">Mobile Phones</a></li>
                                    <li class="menu-item"><a class="menu-link" href="shop-list-right-sidebar.html">Televisions</a></li>
                                    <li class="menu-item"><a class="menu-link" href="shop-list-left-sidebar.html">Video Games</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="single-widget">
                                <h3 class="widget-title">Information</h3>
                                <ul class="widget-menu">
                                    <li class="menu-item"><a class="menu-link" href= "about-us.html">About us</a></li>
                                    <li class="menu-item"><a class="menu-link" href="blog.html">Blog</a></li>
                                    <li class="menu-item"><a class="menu-link" href="shop-grid.html">Weekly Deals</a></li>
                                    <li class="menu-item"><a class="menu-link" href="cart.html">Cart</a></li>
                                    <li class="menu-item"><a class="menu-link" href="sign-in.html">Sign In</a></li>
                                    <li class="menu-item"><a class="menu-link" href="sign-up.html">Sign Up</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="single-widget">
                                <h3 class="widget-title">Customer Service</h3>
                                <ul class="widget-menu">
                                    <li class="menu-item"><a class="menu-link" href="faq.html">Help & FAQs</a></li>
                                    <li class="menu-item"><a class="menu-link" href="term-conditions.html">Terms of Conditions</a></li>
                                    <li class="menu-item"><a class="menu-link" href="privacy-policy.html">Privacy Policy</a></li>
                                    <li class="menu-item"><a class="menu-link" href="refund-policy.html">Online Returns Policy</a></li>
                                    <li class="menu-item"><a class="menu-link" href="shipping-return.html">Shipping & Return</a></li>
                                    <li class="menu-item"><a class="menu-link" href="contact.html">Contact us</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                    <div class="single-widget newsletter-widget">
                        <h3 class="widget-title">Newsletter Sign Up</h3>
                        <p class="newsletter-text">Receive our latest updates about our <br /> products and promotions.</p>
                        <div class="newsletter-form mb-40">
                            <form>
                                <div class="form-group">
                                    <input type="email" class="form-control" id="newsletter" name="newsletter" placeholder="Your Email Address" />
                                    <button type="button" class="subscribe-btn">Subscribe</button>
                                </div>
                            </form>
                        </div>
                        <div class="payment-area">
                            <h3 class="widget-title">We Accepts</h3>
                            <img class="payment-icons" src="{% static 'images/accepts-image.png'  %}" alt="accepts-image" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container-fluid">
            <div class="footer-bottom-wrap">
                <p class="copyright-text">Designed And Developed By Team <a class="brand-name" href="#">Zainiktheme</a> Digital Agency @2021</p>
            </div>
        </div>
    </div>
</footer>
<!-- footer area end here -->

Home/templates/includes/navbar.html
{% load static %}
<nav class="menu-area">
    <ul class="main-menu">
        <li class="menu-item menu-item-has-children">
            <a class="menu-link" href="#">Home <i class="arrow-icon fas fa-angle-down"></i></a>
            <ul class="sub-menu">
                        <a href="{% url 'Home:index' %}" class="footer-brand-logo mb-25"> <img src="{% static 'images/footer-logo.png'%}" alt="footer-logo" /></a>
                <li class="sub-menu-item"><a class="sub-menu-link" href="{% url 'Home:index' %}">Home One</a></li>
                <li class="sub-menu-item"><a class="sub-menu-link" href= "{% url 'Home:index2' %}">Home Two</a></li>
                <li class="sub-menu-item"><a class="sub-menu-link" href="{% url 'Home:index3' %}">Home Three</a></li>
            </ul>
        </li>